set(_CATKIN_CURRENT_PACKAGE "rangeimage")
set(rangeimage_VERSION "0.0.0")
set(rangeimage_MAINTAINER "kaffe <kaffe@todo.todo>")
set(rangeimage_PACKAGE_FORMAT "1")
set(rangeimage_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "efusion")
set(rangeimage_BUILD_EXPORT_DEPENDS "efusion" "roscpp" "rospy" "std_msgs")
set(rangeimage_BUILDTOOL_DEPENDS "catkin")
set(rangeimage_BUILDTOOL_EXPORT_DEPENDS )
set(rangeimage_EXEC_DEPENDS "efusion" "roscpp" "rospy" "std_msgs")
set(rangeimage_RUN_DEPENDS "efusion" "roscpp" "rospy" "std_msgs")
set(rangeimage_TEST_DEPENDS )
set(rangeimage_DOC_DEPENDS )
set(rangeimage_DEPRECATED "")